### ISSUE TITLE
Add inter rater tools

### ISSUE THREAD

**Issue by DOH-SNC1303** [sara-chronister/syndrome-definition-evaluation#15]

**Comment by DOH-TJB0303** [comment]
Additional Checklist of Updates:

- [ ] Adjust EXCEL Template to just say manually review definitions `TRUE`/`FALSE` (instead of specifying the definitions).
- [ ] Rename `Manual_Review` to `Validation_Review`
- [ ] Within each `Output Folder` nested a: 1) `Matched_Elements`, and `Validation_Review` subfolder.
- [ ] Remove `0_Raw_Data` subfolder under `Validation_Review` (just use the files from `Output`).
- [ ] Add `All_(Def1)` and `All_(Def2)` data sets to `Output` to replace `0_Raw_Data`
- [ ] Test `ReviewScale` variables to ensure they are robust against weird user input scale (such as 1-7).

**Comment by DOH-TJB0303** [comment]
We are factoring Review Category Labels (True Positive, False Positive) before feeding the reviewer data to `caret::confusionMatrix()`. Under this format, "Uncertain" Review Category labels are set to NA within the factor, and I believed dropped from the query metric calculations.

@DOH-SNC1303 @DOH-SNC1303 

**Question:** Is there a way to incorporate "Uncertain' review labels into Query performance metrics? I have really only seen 2x2 (TP/FP and TN/FN) so dropping "Uncertain" review categories seems like an ok approach...

**Comment by DOH-TJB0303** [comment]
Considerations for additional SRS variables:

- [ ] Sex
- [ ] Race
- [ ] Ethnicity
- [ ] NCHS Urban-Rural Classification (Patient or Facility Region)
- [ ] Severity of Visit
- [ ] AgeGroup --> not sure how we would want to do this --> ranges of complexity here...

**Comment by DOH-TJB0303** [comment]
12/14/2023:

Added 
`# Create Matched Elements Subfolder
fs::dir_create(paste0(output_folder, "Matched_Elements"))`

to support Matched_Elements subfolder creation (where data is written)
