### ISSUE TITLE
update scripts to work with NSSP Posit environment

### ISSUE THREAD

**Issue by DOH-SNC1303** [sara-chronister/syndrome-definition-evaluation#31]
- [x] replace "\\" with "/"
- [x] have NSSP add "pacman"
- [x] add code for pacman to be installed automatically if not already installed

**Comment by TylerBonnellSnoco** [comment]
Tested it on my end -- there were a few errors which I implemented small fixes for. I have attached a small Word document indicating the nature of the error, the location of the error, and the implemented solution.

**I should have directly just entered those here -- sorry!**

[Branch 31 Testing Error Notes.docx](https://github.com/user-attachments/files/17136988/Branch.31.Testing.Error.Notes.docx)

Everything was running smoothly for me after those tweaks. Once you are comfortable, may be good to submit as a pull request, and then both of us do a final look through of the Code Diffs to double check we are ready for prime time!

**Comment by DOH-SNC1303** [comment]
@TylerBonnellSnoco did you push your changes to GitHub? I was looking for them to do the pull request but didn't see them anywhere.

**Comment by TylerBonnellSnoco** [comment]
Hi @DOH-SNC1303, it looks like my permissions are blocked to push to this particular branch (I have 5 changes sitting in my look Git repository to push up) -- I am getting an HTTPS 403 code (forbidden).

This may be due to Branch Protection rules in place: https://chatgpt.com/share/66fde8de-a630-8011-b58b-5520b124b0d1

I am happy to work through this bug with you or just send a zip file to finish the updates (in the short term).
